### PR TITLE
Dev/ahn nath: Add social media icons with links to representative card

### PR DESCRIPTION
**Pull request by ahn-nath**
Issue: #295 

🖼️: Front-end
⚙️: Back-end
🏗️: Architecture

We have completed the following:
**Process and implementation**
- **[X] ⚙️ Identify social media URLs from the identifiers property.**
- To identify social media URLs from the URLs I used Postman and chose: **Instagram, Facebook, Twitter, and Youtube** as my targets. 
**- [X] ⚙️ Improve the back-end API schema to send back social media profiles in an array.**
- I am using a function that uses the “identifiers” attribute from the representative JSON object as an argument and process the item with a switch statement to get the relevant sites and apply filters as required. I get the social media name, the social media value (username), and set the social media icon to use for it on the front end (example: fa-instagram). Then the funciton returns the array as a new property of the representative JSON that will be sent to the frontend.
**- [X] 🖼️ Display icons for known social media platforms.**
I have downloaded the FontAwesome library and have implemented it as specified in the official documentation. I felt that it was more practical than downloading svg files one by one, specially since we may be using more social media icons in the future. 

Looking forward to your comments.

### CODE REVIEW

**Review by paramsiddharth — COMMENTED** [review]
@ahn-nath Looks good to me, Nath. I appreciate the clean and organized implementation you've done, especially with the separation of concerns and maintaining the code style.

Have you tested it out on some zip codes? If so, could you share some screenshots of what it looks like? It would help ensure the results are consistent with the proposed UI.

**Comment by ahn-nath** [comment]
@paramsiddharth

Hi, Param. Thanks.

Yes, I have tested it several times, normally, with zip codes corresponding to Washington. I cannot upload a screenshot since I have internet connection issues right now, and it prevents me from connecting to Codespaces. Tomorrow I will be at a place with stable and high speed connection and will attach it. If I happen to have the opportunity today, I will do so as well.

**Comment by ahn-nath** [comment]
@paramsiddharth
 
**The screenshots:**
Postal code: 98104
image

Postal code: 32118
image

**Review by manishapriya94 — APPROVED** [review]
Looks great!

**Pull request merged**
