### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by smgraywood**
**Issue**
Currently a code of conduct is missing. 
**Fix**
Adding Contributor Covenant.

Closes https://github.com/ProgramEquity/amplify/issues/409

### CODE REVIEW

**Comment by therzka** [comment]
Thanks so much! If you add the text: `Closes https://github.com/ProgramEquity/amplify/issues/409` to your PR description, that issue will automatically be closed when you merge!

**Comment by therzka** [comment]
Thanks so much! If you add the text: `Closes https://github.com/ProgramEquity/amplify/issues/409` to your PR description, that issue will automatically be closed when you merge!

**Review by therzka — APPROVED** [review]

**Review by evelynluu2 — APPROVED** [review]

**Comment by paramsiddharth** [comment]
Congratulations on getting your second PR merged! ✨

**Comment by smgraywood** [comment]
> Congratulations on getting your second PR merged! ✨

Thank you! 😄

**Pull request merged**
