### PR TITLE
707-Letter-Madlib-customization

### PR DESCRIPTION
**Pull request by mianmiantea2019**
- Create 4 drop downs with the above questions in display letter

### CODE REVIEW

**Comment by davidchapuis** [comment]
Hi @mianmiantea2019 thanks, great work
in .env.example file can you replace "TEST_LOB_API_KEY" by "LOB_API_KEY"  ?
It should work this way :)

**Comment by mianmiantea2019** [comment]
> Hi @mianmiantea2019 thanks, great work in .env.example file can you replace "TEST_LOB_API_KEY" by "LOB_API_KEY" ? It should work this way :)

Hi David, 
Could you let me know the next steps after replacing LOB_API_KEY in the .env file? I've rerun the integration test, but it's still failing. Am I missing any steps?

**Comment by davidchapuis** [comment]
> > Hi @mianmiantea2019 thanks, great work in .env.example file can you replace "TEST_LOB_API_KEY" by "LOB_API_KEY" ? It should work this way :)
> 
> Hi David, @davidchapuis Could you let me know the next steps after replacing LOB_API_KEY in the .env file? I've rerun the integration test, but it's still failing. Am I missing any steps?

Hi @mianmiantea2019 here you last commit says Merge branch 'ProgramEquity:main' into 707-Letter-Madlib-customization

> > Hi @mianmiantea2019 thanks, great work in .env.example file can you replace "TEST_LOB_API_KEY" by "LOB_API_KEY" ? It should work this way :)
> 
> Hi David, @davidchapuis Could you let me know the next steps after replacing LOB_API_KEY in the .env file? I've rerun the integration test, but it's still failing. Am I missing any steps?

Hi CHristy @mianmiantea2019 did you modify the .env.example file and run Prettier? 
Here your last commit says you are trying to merge main branch into your branch

**Comment by Alex-is-Gonzalez** [comment]
@mianmiantea2019  and @davidchapuis is this PR good to close out since it was resolved on a different PR?

**Comment by mianmiantea2019** [comment]
> @mianmiantea2019 and @davidchapuis is this PR good to close out since it was resolved on a different PR?

Hi Alex, yea, the  issue was resolved on a different PR, so this PR is good to close out. Thank you!

**Pull request closed without merging**
