### PR TITLE
[Experiment] Use Open States API instead of the Google Civic API

### PR DESCRIPTION
**Pull request by JamesMGreene**
[Experiment] Use Open States API instead of the Google Civic API

Closes #121

Towards https://github.com/ProgramEquity/amplify/issues/29

:warning: The results for the Open States API definitely seem a lot smaller (fewer reps returned) and more inconsistent on some parts (e.g. office addresses). It is also missing U.S. Senators. 😭  It _does_, however, include a photo URL. 😅

### CODE REVIEW

**Comment by JamesMGreene** [comment]
I checked with the Open States folks at Civic Eagle. They suggested we could use this alternative backend call to get the U.S. Senators factored in, e.g.
```
https://openstates.org/find_your_legislator/?lat=44.65&lon=-93.14&address=55024&state=json=json
```

_buuuuut_ it's outside of the official API so no idea on if we will hit rate limiting, and the response schema is very tightly scope such that it's missing details we want like office addresses. 👎🏻 

I'm going to make the call and say that the Open States API, as it is today, does not meet our current needs. 🙅🏻‍♂️

**Comment by manishapriya94** [comment]
@Param Siddharth here are election calendars..wondering if we should almost be using ballotpedia's open API to create flags for refreshing cicero's cache? https://ballotpedia.org/Elections_calendar

cc for visibility: @James Greene this is regarding the block we ran into with the pictures for reps and how we should cache what cicero API returns. @Param Siddharth was speaking to how we can create a reps data structure similar to campaigns API. Ballotpedia would help us understand when to refresh the cache and by jursidiction

**Comment by paramsiddharth** [comment]
@manishapriya94 You'd want to look at this.

Source: https://ballotpedia.org/API-documentation/faq

image

image

**Comment by JamesMGreene** [comment]
Cicero data includes a field that indicates when the official's term is set to expire, which is probably a pretty strong cue to utilize in most cases. Either way, I think the Open States API (not Cicero) is out of the running as far as I can tell. 🙅🏻

**Comment by paramsiddharth** [comment]
> Cicero data includes a field that indicates when the official's term is set to expire, which is probably a pretty strong cue to utilize in most cases. Either way, I think the Open States API (not Cicero) is out of the running as far as I can tell. 🙅🏻

@JamesMGreene Wow, James! Do you think we might be able to use the same while implementing the cache refreshing strategy?

**Comment by JamesMGreene** [comment]
> Do you think we might be able to use the same while implementing the cache refreshing strategy?

It feels like it could be at least a good default to drive refreshes with. 👍🏻 

The field I was referring to is called `valid_to`.

From https://cicero.azavea.com/docs/#official-object:

> `valid_to`: Date the official's term in office expires. This date would be extended if the official wins re-election.

**Pull request closed without merging**
