### PR TITLE
Fixed Campaign Page Responsivity for Mobile

### PR DESCRIPTION
**Pull request by sammychinedu2ky**
Fix for https://github.com/ProgramEquity/amplify/issues/334
image

image
@paramsiddharth

### CODE REVIEW

**Comment by paramsiddharth** [comment]
@sammychinedu2ky Good job on the PR, Samson~! I love the change you made to the UI, and the fact that you added the screenshots to the PR. I'll test it out and continue the PR review. :) Getting back to you soon.

**Comment by sammychinedu2ky** [comment]
> @sammychinedu2ky Good job on the PR, Samson~! I love the change you made to the UI, and the fact that you added the screenshots to the PR. I'll test it out and continue the PR review. :) Getting back to you soon.

Thanks 🙌😅

**Review by thyeggman — APPROVED** [review]
The PR looks good to me!  The screenshots are good, but it would be helpful to show that the UI doesn't break when switching between sizes by including a video.  If you're on a Mac, you can record your screen (or a part of it) with `cmd+shift+5`, or on Windows there are tools for screen recording if you press `win+g`.  Then you can record yourself resizing the window :)

**Review by paramsiddharth — CHANGES_REQUESTED** [review]
@sammychinedu2ky Hey Sam! :) Good job on the PR, excellent work! I loved how you rearranged the components and completely revamped the mobile UI/UX. It looks way better than it used to.

I think the only change I'd request from you is to make the representative list less wide on desktop devices. Mine, for example, is a very high-resolution desktop view, and the rep list is unnecessarily wide. I think that would be achievable using some Tailwind classes with breakpoints, too. 😊

image

**Comment by sammychinedu2ky** [comment]
Ok thanks for the feedback. I would work on that 😅🙌

**Comment by sammychinedu2ky** [comment]
is this okay @paramsiddharth 
image

**Review by paramsiddharth — APPROVED** [review]
@sammychinedu2ky Good job, Sam! :) The redesign looks really professional and responsive on different device sizes. I just tested it out locally and I think we're good to go.

Excellent work, Sam! :) Let's wait for Jacob (@thyeggman) to review and then we can proceed with merging your PR.

**Comment by sammychinedu2ky** [comment]
Cool thanks 🙌🍷.

**Review by thyeggman — APPROVED** [review]
Looks great, let's merge it!

**Comment by thyeggman** [comment]
Ah, looks like there are still some integration tests that need to be fixed.  We can take a look at them during the pair hours if you want.

**Pull request merged**
