### PR TITLE
Update to Action complete issue #215

### PR DESCRIPTION
**Pull request by DietBepis1**
- Adds basic functionality to ActionComplete.vue
- Implements a carousel in CauseCarousel.vue
- Creates a generic CampaignCard component to reduce code repetition.

The purpose of the PR is to prep the completion page for adding persisted campaign information from before the Stripe redirect. This way, we can repopulate representative information and user information that is currently lost.

### CODE REVIEW

**Comment by aneelac22** [comment]
Can you resolve conflicts?

**Comment by DietBepis1** [comment]
Hey @aneelac22 , I fixed the merge conflict and it should be good. I had to update the integration test that is failing to use a different parameter from Stripe, so the code in my most recent commit will fix that, but cannot pass the test without a bypass. Let me know if you have questions.

**Comment by manishapriya94** [comment]
@paramsiddharth

**Comment by paramsiddharth** [comment]
@DietBepis1 Let's look at the PR in tonight's pair hours!

P. S. Yes, it is night in IST, hehe.

**Comment by paramsiddharth** [comment]
@DietBepis1 The conflict in `RepresentativeCard.vue` seems to be a rather simple one i.e. A few class names and HTML properties. :) You can resolve them whenever you get time and let me know, I'll merge it!

**Comment by paramsiddharth** [comment]
@DietBepis1 I fixed the merge conflicts. :) @manishapriya94 Finally merging the PR now.

**Pull request merged**
