### PR TITLE
Updates script/bootstrap so it works on codespace launch

### PR DESCRIPTION
**Pull request by gdomingu**
Noticed that the `script/bootstrap` would fail on the `brew` steps because brew wasn't being added to the path when creating it from a codespace. This should fix that. 

Also updates package.json because was complaining about not being able to resolve less-loader@5.0.0 for some other packages.

### CODE REVIEW

**Review by paramsiddharth — COMMENTED** [review]
Hey @gdomingu ! Just a question here — Did you regenerate the lockfile here or did you modify it directly?

**Comment by gdomingu** [comment]
> Hey @gdomingu ! Just a question here — Did you regenerate the lockfile here or did you modify it directly?

@paramsiddharth I ran `npm install --legacy-peer-deps` and it regenerated it for me.

**Review by paramsiddharth — DISMISSED** [review]
Alrighty. Looks good to me!

**Comment by JamesMGreene** [comment]
@gdomingu Ideally, running `script/bootstrap` shouldn't be necessary for Codespaces if we setup the container correctly. 😅  Did you find that it was needed for you?

**Review by JamesMGreene — APPROVED** [review]

**Pull request merged**
