### PR TITLE
Create Unit Tests GitHub Action Workflow

### PR DESCRIPTION
**Pull request by rsensenig**
# Description

This is a GitHub Action workflow for running unit tests either manually, or when a pull request is opened or reopened. This workflow is in [unit-tests.yml](https://github.com/ProgramEquity/amplify/blob/unit-tests-config/.github/workflows/unit-tests.yml).

## Type of change

New OSS workflow

## Status
Ready for Review

### CODE REVIEW

**Comment by DietBepis1** [comment]
I looked at this compared to our integration tests Action config and it looks good to me. Plus, I can see successful runs in our Action history so I am going to approve it. We can disable it if we run into some weird issue.

**Review by DietBepis1 — APPROVED** [review]

**Comment by rsensenig** [comment]
> I looked at this compared to our integration tests Action config and it looks good to me. Plus, I can see successful runs in our Action history so I am going to approve it. We can disable it if we run into some weird issue.

Thanks @DietBepis1! It appears that this PR is still blocked from being merged into main. @paramsiddharth do you need to approve this PR as well before it can be merged?

**Comment by DietBepis1** [comment]
> > I looked at this compared to our integration tests Action config and it looks good to me. Plus, I can see successful runs in our Action history so I am going to approve it. We can disable it if we run into some weird issue.
> 
> Thanks @DietBepis1! It appears that this PR is still blocked from being merged into main. @paramsiddharth do you need to approve this PR as well before it can be merged?

Yep, just need approval from Mr. @paramsiddharth.

**Review by paramsiddharth — APPROVED** [review]

**Comment by paramsiddharth** [comment]
@rsensenig Good job, Rachel! <3

**Pull request merged**
