### PR TITLE
Awkward word wrapping fix

### PR DESCRIPTION
**Pull request by mariah622**
Problem:

Some of the newer campaigns we've added for Sunrise have longer names. Some of these are exhibiting some awkward word-wrapping, e.g:

159747842-dd297e80-838c-47a6-833c-ae7e5f585cef

Solution:

Add word-break styling to campaign title

### CODE REVIEW

**Comment by paramsiddharth** [comment]
Looks like what's going wrong here is a formatting check. All you need to do is run:
```bash
npm run format
npm run lint
```

Commit the updated changes and you're good to go.

P.S. If you install the _'Prettier'_ extension in VSCode and configure it to auto-format for the current workspace, it gets much easier!

**Review by paramsiddharth — DISMISSED** [review]

**Review by thyeggman — DISMISSED** [review]

**Review by DietBepis1 — CHANGES_REQUESTED** [review]
Mariah, it appears that <v-card-title /> has that weird word-wrapping from a bug (https://github.com/vuetifyjs/vuetify/issues/9130). For the sake of consistency and best utilization of Vuetify, I would suggest changing the <v-card-title /> tag into an <h# /> and using one of Vuetify's built-in header classes (https://vuetifyjs.com/en/styles/text-and-typography/).

**Comment by DietBepis1** [comment]
Mariah, the new change looks good to me. I think this can be merged. 👍🏽

**Review by paramsiddharth — APPROVED** [review]

**Comment by paramsiddharth** [comment]
@ProgramEquity/dev-leads Please re-review the PR and merge it. After #265, this PR is mergeable and the tests are passing. @DietBepis1 already approved the PR.

**Review by manishapriya94 — APPROVED** [review]

**Pull request merged**
